### ISSUE TITLE
Update peer dependencies?

### ISSUE THREAD

**Issue by dingo-d** [infinum/js-linters#13]
I am requiring `"@infinumjs/eslint-config": "^1.1.0"` in a project and I got:

> @infinumjs/eslint-config@1.1.0 requires a peer of eslint@4.x but none is installed. You must install peer dependencies yourself

I also have `"eslint": "^5.4.0"` in my `devDependencies`, and the linter works fine.

Should the `peerDependencies` be set to `>=4.x`?

https://github.com/infinum/js-linters/blob/b83344a623f5566750926fd63d930b55c31b91fa/eslint-config/package.json#L24

**Comment by kristijanbambir** [comment]
Maybe the peer dependency should be updated to 5.x.

**Comment by DarkoKukovec** [comment]
If there is no reason to deprecate eslint 4 support, we could go with`"^4.x || ^5.x"`. Something like `>=4.x` is too dangerous, since we can't know if everything will work with eslint 6

**Comment by kristijanbambir** [comment]
I have published new package versions.
