### ISSUE TITLE
class-methods-use-this

### ISSUE THREAD

**Issue by isBatak** [infinum/js-linters#4]
When using eslint-config/base I often get this warning `[eslint] Expected 'this' to be used by class method 'onExample'. (class-methods-use-this)`, can we disable this rule because sometimes I really don't need to use `this` inside method... for example, with jQuery on click handler I can get target element form event passed to the method...

**Comment by kristijanbambir** [comment]
I agree, we should remove this rule. If @DarkoKukovec and @safo6m agree, @isBatak please create a PR.
