### ISSUE TITLE
Check deprecated rules

### ISSUE THREAD

**Issue by DarkoKukovec** [infinum/js-linters#7]
I have a report from a project that the following rules are returning a deprecated error:
* valid-typeof
* no-var-self
* no-stateless-class
* no-empty-interfaces
* no-duplicate-case
* use-default-type-parameter
* no-void-expression
* await-promise
* match-default-export-name
* no-floating-promises
* no-for-in-array
* no-unsafe-any
* promise-function-async
* restrict-plus-operands
* completed-docs
* no-unnecessary-qualifier
* no-unnecessary-type-assertion
* strict-boolean-expressions

**Comment by nives113** [comment]
Fixed in version '2.0.0-beta.3'
