### ISSUE TITLE
Update ESLint peer dependencies to 8

### ISSUE THREAD

**Issue by kristijanbambir** [infinum/js-linters#73]
The current configs no longer work with ESLint 7 anyways, so we might as well set the peer dependency to `>=8`.

**Comment by isBatak** [comment]
@kristijanbambir isn't this on PR already and approved? https://github.com/infinum/js-linters/pull/71
What is blocking this PR form merging?

**Comment by kristijanbambir** [comment]
@isBatak Good catch, I completely missed this. @adrianbicanic you can go ahead and merge that PR.

**Comment by adrianbicanic** [comment]
This issue has been resolved with https://github.com/infinum/js-linters/pull/71.
